//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAPI.DataSources
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_FACULTY
    {
        public string FAC_ID { get; set; }
        public string FAC_NAME_THAI { get; set; }
        public string FAC_NAME_ENG { get; set; }
        public string CAMP_ID { get; set; }
        public string FAC_TEL_FAX { get; set; }
        public Nullable<short> STAFF_NUMBER { get; set; }
        public Nullable<short> EMP_NUMBER { get; set; }
        public string FAC_DESC { get; set; }
        public string OLD_FAC { get; set; }
        public string SHORT_NAME_THAI { get; set; }
        public string N_FAC_ID { get; set; }
        public string ISCED_ID { get; set; }
        public string FAC_GRP_ID { get; set; }
    }
}
