//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAPI.DataSources
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TITLE
    {
        public string TITLE_ID { get; set; }
        public string TITLE_NAME_THAI { get; set; }
        public string TITLE_NAME_ENG { get; set; }
        public string TITLE_SHORT_THAI { get; set; }
        public string TITLE_SHORT_ENG { get; set; }
    }
}
