//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAPI.DataSources
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_STAFF
    {
        public string STAFF_ID { get; set; }
        public string STAFF_TYPE_ID { get; set; }
        public string STAFF_NAME_THAI { get; set; }
        public string STAFF_NAME_ENG { get; set; }
        public string STAFF_SNAME_THAI { get; set; }
        public string STAFF_SNAME_ENG { get; set; }
        public string TITLE_ID { get; set; }
        public string SEX_ID { get; set; }
        public string STAFF_BIRTH_DATE { get; set; }
        public string PROV_ID { get; set; }
        public string GRAD_ID { get; set; }
        public string MARRIED_ID { get; set; }
        public string RELIGION_ID { get; set; }
        public string STAFF_SEAT_ID { get; set; }
        public string STAFF_TAX_NUM { get; set; }
        public string STAFF_APPROV_NUM { get; set; }
        public string POS_ID { get; set; }
        public Nullable<byte> SALARY_C { get; set; }
        public Nullable<decimal> SALARY_RANK { get; set; }
        public Nullable<int> SALARY { get; set; }
        public Nullable<decimal> STAFF_SAL_STEP { get; set; }
        public Nullable<short> STAFF_APPROV_YEAR { get; set; }
        public string STAFF_ACCEPT_DATE { get; set; }
        public string CAMPUS_ID { get; set; }
        public string PLAN_ID { get; set; }
        public string JOB_ID { get; set; }
        public string FAC_ID { get; set; }
        public string DEPT_ID { get; set; }
        public string SECT_ID { get; set; }
        public string STAFF_BLOOD { get; set; }
        public string STAFF_PICTURE { get; set; }
        public string STAFF_DEPART { get; set; }
        public string STAFF_EMAIL { get; set; }
        public string STAFF_END { get; set; }
        public string TITLE_NAME { get; set; }
        public string STAFF_STEP_TYPE { get; set; }
        public string UNIT_ID { get; set; }
        public string STAFF_TYPE { get; set; }
        public string DATE_ID { get; set; }
        public string STAFF_OUT { get; set; }
        public string STAFF_PERS_ID { get; set; }
        public string OLD_STAFF_ID { get; set; }
        public string MAIN_MAJOR { get; set; }
        public string NEWID { get; set; }
        public string STAFF_DATE_OUT { get; set; }
        public Nullable<decimal> NUM_REST { get; set; }
        public string STAFF_FULL_SAL { get; set; }
        public string SUBUNIT_ID { get; set; }
        public Nullable<byte> OLD_SALARY_C { get; set; }
        public Nullable<short> OLD_SALARY { get; set; }
        public string ADM_POS { get; set; }
        public string STAFF_NO { get; set; }
        public Nullable<short> BUDGET_SALARY { get; set; }
        public Nullable<short> BUDGET_TIME { get; set; }
        public Nullable<short> WORK_TIME { get; set; }
        public string WORK_COND { get; set; }
        public string INS_ID { get; set; }
        public Nullable<short> USE_YEAR1 { get; set; }
        public Nullable<short> USE_YEAR2 { get; set; }
        public Nullable<short> YEAR_BLANK { get; set; }
        public string POS_LACK { get; set; }
        public Nullable<short> INCOME_SALARY { get; set; }
        public Nullable<byte> WORK_TIME_DAY { get; set; }
        public Nullable<byte> EXIT_STS { get; set; }
        public string P_RACE { get; set; }
        public string AMT_TYPE { get; set; }
        public string P_COUNTRY { get; set; }
        public string P_CITIZEN { get; set; }
        public string WORK_BEGIN { get; set; }
        public string WORK_END { get; set; }
        public Nullable<int> SALARY_OCT_PYEAR { get; set; }
        public Nullable<byte> SALARY_C_OCT { get; set; }
        public Nullable<decimal> STEP_OCT { get; set; }
        public Nullable<decimal> SAL_STEP_OLD { get; set; }
        public Nullable<decimal> REST_COLL { get; set; }
        public Nullable<decimal> REST_USED { get; set; }
        public string TITLE_NAME2 { get; set; }
        public Nullable<decimal> PERCENT_INC { get; set; }
        public string TITLE2_NAME_ENG { get; set; }
        public Nullable<byte> ENTRY_NO { get; set; }
        public string TITLE_NAME3 { get; set; }
        public string TITLE_NAME3_ENG { get; set; }
        public string EMP_TYPE { get; set; }
        public string EMP_SOURCE { get; set; }
        public string LOGIN { get; set; }
        public string MODIFY_DATE { get; set; }
        public string MODIFY_USER { get; set; }
        public string EMP_HEAD { get; set; }
    }
}
