//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAPI.DataSources
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonelOracleEntities : DbContext
    {
        public PersonelOracleEntities()
            : base("name=PersonelOracleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<P_STAFF> P_STAFF { get; set; }
        public virtual DbSet<C_TITLE> C_TITLE { get; set; }
        public virtual DbSet<C_FACULTY> C_FACULTY { get; set; }
    }
}
